version: "3.8"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
 
    ws.tomcat.1:
        container_name: ws.tomcat.1
        image: tomcat:8.5.57-jdk8-corretto
        volumes:
          - .\ws.war:/usr/local/tomcat/webapps/ws.war:ro
          - .\logs\ws.tomcat.1:/usr/local/tomcat/logs
        ports:
          - "8087:8080"
          - "8000:8000"
          - "8060:8060"
        environment:
          - TZ=America/Sao_Paulo
          - TOMCAT_PASS=admin
          - OMS_LOG_DIR=/usr/local/tomcat/logs
          - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
          - JAVA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=8060 -Dcom.sun.management.jmxremote.rmi.port=8060 -Xmx2g -Xms32m -XX:+PrintGCDetails -Xloggc:/usr/local/tomcat/logs/gclog
        links:
          - redis
        networks:
            app_net:
                ipv4_address: 172.16.238.20
                
    ws.tomcat.2:
        container_name: ws.tomcat.2
        image: tomcat:8.5.57-jdk8-corretto
        volumes:
          - .\ws.war:/usr/local/tomcat/webapps/ws.war:ro
          - .\logs\ws.tomcat.2:/usr/local/tomcat/logs
        ports:
          - "8086:8080"
          - "8001:8000"
          - "8050:8060"
        environment:
          - TZ=America/Sao_Paulo
          - TOMCAT_PASS=admin
          - OMS_LOG_DIR=/usr/local/tomcat/logs
          - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
          - JAVA_OPTS=-Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=8060 -Dcom.sun.management.jmxremote.rmi.port=8060 -Xmx2g -Xms32m -XX:+PrintGCDetails -Xloggc:/usr/local/tomcat/logs/gclog
        links:
          - redis
        networks:
            app_net:
                ipv4_address: 172.16.238.21