version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9190:9090
    networks:
      - prometheus-compose-network
    volumes:
      - .\prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3100:3000

networks: 
  prometheus-compose-network:
    driver: bridge
