version: "3.8"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
    
    nginx:
        container_name: nginx_docker
        image: nginx
        volumes:
          - .\nginx.conf:/etc/nginx/nginx.conf:ro
          - .\logs\nginx:/var/log/nginx
        ports:
          - "9081:9081"
        environment:
            TZ: "America/Sao_Paulo"       
        networks:
            app_net:
                ipv4_address: 172.16.238.10
