version: "3.8"

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"

services:
    
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - ./config/redis.conf:/redis.conf
        environment:
            TZ: "America/Sao_Paulo"                   
        command: ["redis-server", "/redis.conf"]
        networks:
            app_net:
                ipv4_address: 172.16.238.11
